// //////////////////////////////////////// Error Handling //////////////////////////////
try{

    // ...normal code. 


} catch (err) {    // err is error object.

console.log(err);
    // ...handling error. 
};



// expm

let a = 5;
let b = 10;
console.log(a);
console.log(b);
console.log(a + b);
console.log(a + b);
try {
    console.log(a + c);  // error.

}catch (err) {

    console.log(err);
}
console.log(a + b);
console.log(a + b);
console.log(a + b);
console.log(a + b);
